### ISSUE TITLE
Vavoo suche...

### ISSUE THREAD

**Issue by Basti83x** [michaz1988/repo#17]
Hi. Hab da mal eine frage. Kannst du mir vielleicht sagen wie ich eine verlinkung zur vavoo Film/Serien suche hinbekomme. Also im sikn menü. Wenn ich den üblichen weg nutze und den eintrag auswähle. Komm ich nach der auche immer ins menü für datein. Das suchergebniss taucht kurz auf und dann ist sie wieder weg.

Für filme ist jetzt der befehl:

<action>ActivateWindow(Videos,"plugin://plugin.video.vavooto/?action=search&amp;id=movie.popular",return)</action>

Für serien ist jetzt der befehl:

<action>ActivateWindow(Videos,"plugin://plugin.video.vavooto/?action=search&amp;id=series.popular",return)</action>

Vielleicht weist du ein befehl der funktioniert.

Schon mal danke für deine hilfe.

**Comment by Basti83x** [comment]
Hab festgestellt das in der neusten version 5.9.3.5 keine filme/serien funktionieren bin jetzt zurück zur version 5.8.6

**Comment by michaz1988** [comment]
ActivateWindow(Videos,"plugin://plugin.video.vavooto/?action=search&amp;id=series.popular",return)

mit version 5.9.3.5 läuft bei mir mit kodi 20.1

**Comment by Basti83x** [comment]
Ich hab kodi 19.5. Hab auch nochmal probiert neu zu installieren half aber nix geht nur live tv . Leider keine filme/serien

**Comment by Basti83x** [comment]
Hier ist der fehler sus dem log. Falls du noch was brauchst sag es.

ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'KeyError'>
                                                   Error Contents: '_bootlocale'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vavooto/main.py", line 32, in <module>
                                                       else: getattr(vjackson, "_%s" % action)(params)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vavooto/resources/lib/vjackson.py", line 69, in _list
                                                       o = future.result()
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/concurrent/futures/_base.py", line 432, in result
                                                       return self.__get_result()
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
                                                       raise self._exception
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
                                                       result = self.fn(*self.args, **self.kwargs)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vavooto/resources/lib/vjackson.py", line 38, in createListItem
                                                       data = utils.get_meta(params)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vavooto/resources/lib/utils.py", line 95, in get_meta
                                                       set_cache({"id": param["id"]}, meta)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vavooto/resources/lib/utils.py", line 38, in set_cache
                                                       with open(file+".json", "w") as k: json.dump(data, k, indent=4)
                                                   KeyError: '_bootlocale'
                                                   -->End of Python script error report<--

**Comment by Basti83x** [comment]
Vielleicht hilft der fehler log ja

**Comment by Basti83x** [comment]
https://github.com/michaz1988/repo/assets/130665959/0ef0df0e-11eb-4f47-904e-76475765e97f

Hier mal ein beispiel video wie die such mit dem befehl bei mir läuft

**Comment by Basti83x** [comment]
Hatte das versehentlich geschlossen

**Comment by michaz1988** [comment]
hab jetzt mal alles so wie du versucht mit kodi 19.5 bei version 5.9.3.6 funktioniert bei mir alles

**Comment by Basti83x** [comment]
Jo mit neuer version geht wieder alles..
