### ISSUE TITLE
Vavoo

### ISSUE THREAD

**Issue by Basti83x** [michaz1988/repo#18]
Hi in der neusten version 5.9.3.5 funktionieren keine filme/serien. Ist das bekannt?

Kodi 19.5

**Comment by Basti83x** [comment]
ERROR : EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'KeyError'>
Error Contents: 'bootlocale'
Traceback (most recent call last):
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vavooto/main.py", line 32, in
else: getattr(vjackson, "%s" % action)(params)
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vavooto/resources/lib/vjackson.py", line 69, in _list
o = future.result()
File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/concurrent/futures/_base.py", line 432, in result
return self.__get_result()
File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
raise self._exception
File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vavooto/resources/lib/vjackson.py", line 38, in createListItem
data = utils.get_meta(params)
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vavooto/resources/lib/utils.py", line 95, in get_meta
set_cache({"id": param["id"]}, meta)
File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.vavooto/resources/lib/utils.py", line 38, in set_cache
with open(file+".json", "w") as k: json.dump(data, k, indent=4)
KeyError: '_bootlocale'
-->End of Python script error report<--

**Comment by michaz1988** [comment]
ist behoben mit version 5.9.3.6 
war ein ganz komischer fehler....
